### ISSUE TITLE
[Bug] NullReferenceException

### ISSUE THREAD

**Issue by iRebbok** [northwood-studios/LocalAdmin-V2#1]
# Issue
When the server starts, the NRE crashes.

![Image](https://i.imgur.com/ElcJZDq.png)

I had the same error when building my own branch [feature/logging](https://github.com/iRebbok/LocalAdmin-V2/tree/feature/logging), but I did not pay attention to it.

Please note that my changes do not affect anything that could break this, it was probably already broken before.

# Steps to Reproduce
Start LocalAdmin and enter something.

# Specifications
- **OS: Windows 10.0.18363 (win10-x64)**
- **LocalAdmin version: 2.2.0**
- **SCPSL version: 9.1.3**

**Comment by zabszk** [comment]
Hi.
Version 2.2.0 is compatible only with game version 10.0.0 (will be released soon) or newer, because we have changed the communication protocol (from files to local TCP server). In this case lack of output is normal (LA is waiting for a TCP connection, but older game of the version won't connect) and that's the reason of this exception when sending a command.

We will fix this exception by adding an additional check to make sure that game server is connected to LA before sending commands.

**Comment by iRebbok** [comment]
Hi.
I understood, but didn 't know that was the case.

**Comment by zabszk** [comment]
Hi.
LocalAdmin 2.2.1 should have this issue fixed, but we will wait for the QA tests to confirm it.
