### ISSUE TITLE
Possible Plugin Manager Rewrite

### ISSUE THREAD

**Issue by ALEXWARELLC** [northwood-studios/LocalAdmin-V2#89]
This issue will serve as a QnA for what I hope will become the new plugin manager.

Basically this is how it'll work. There will be a list of NWAPI plugins which have been submitted and strictly approved by plugin moderators or NW developers. Then, whenever the server owner wants to install a plugin, all they have to do is give the name or id of the plugin and let the LA install it. Plugins can be updated, reinstalled, uninstalled and validated from the LA.

The plugins can be hosted wherever, but GitHub will be prioritised.

Each plugin in the JSON list should contain the following keys:
1. ID - this can be used to identify a plugin and install it. This is a PRIMARY item, there cannot be a duplicate.
2. Name - A display name for the plugin.
4. Download URL - Where can the plugin be downloaded. This can be restricted how you wish.
5. Repository URL - This can show people where to find the source code of the plugin.
6. Author - The person who wrote the plugin.

Public methods such as 'Install()', 'Update()', 'Uninstall()' etc will be located in the command class. All internal methods will be located in internal classes (e.g What's currently available. You already know)

When a plugin is installed, it'll update a file containing information about every plugin and if it is a verified plugin or not.

This can and will need to be expanded on but feel free to correct me or give feedback. If you want to contribute to the PR (Draft), feel free to.

Would love to get suggestions. And a lot of help :p

**Comment by ALEXWARELLC** [comment]
Update: I configured git incorrectly so I haven't uploaded whatever I could get done before I have to run some errands but I'll be back to create the pr.

**Comment by ALEXWARELLC** [comment]
No Exiled support bc exiled stinky.

**Comment by zabszk** [comment]
Hi,
First of all - please try to be polite. I understand that you might not like some specific modding framework, but LA repo is not a place to post personal opinions (especially without any reasoning and in impolite way). Make sure to update the issue content to reflect the change.

Secondly - could you tell me more about the rework? What's the exact purpose and what will be changed? Do I understand correctly that LA will **only** allow to install plugins from some approved list?

**Comment by ALEXWARELLC** [comment]
Ok, so about the framework thing, it was me being tired at 4:30am realising you wont accept allowing Exiled plugins in the rewrite so I stupidly write that unnecessary comment which my brain thought was funny at the time.

The main purpose of the rewrite was mostly due to a feeling of general over complexity when using a system which doesn't seem very user friendly. The approach I want to try out is having a simple way of installing, updating and validating plugins using a much better system which can be moderated to stop potentially harmful or malicious plugins which server owners may be tricked into installing. Also the current system is a little flawed as it relays on the server owner to provide a Personal Auth Token and as far as I know, if instead you used the kind of system, I'm trying to produce, you could actually have an experience which makes hosting a server on my hosting platform, a little easier. Considering most new server owners I have seen have struggled to find even the most popular plugins, it seems way more beneficial if instead, the LA could be used to search for & manage plugins (NWAPI or Exiled if your ok with it.) This is a feature that could improve general usability of the LA.

Like I have said many times before. This is more a proof of concept which is why it's a draft pr. I want to iron out any potential issues or exploits before even thinking about requesting a merge.

The currently inserted url is owned by me and is solely used for trying to make the JSON reader work. (I'm kinda stuck on that one) It WILL NOT be used in any production build.

Thanks, and sorry for any interpreted rudeness.

**Comment by zabszk** [comment]
Hi,

> which can be moderated to stop potentially harmful or malicious plugins which server owners may be tricked into installing
That's why the big warning exists. Server owners can be tricked to install a malicious plugin by being asked to upload that plugin. Of course it's easier to issue a command than put a couple of files, but the reality is that the only safe way is to require approval for every NEW VERSION of every plugin and have every plugin deeply analyzed. That's completely not doable - analysis of a complex plugin can take a couple of days. Now imagine what happens if we release a new SCP:SL version - every approved plugin gets updated within hours and someone needs to review every new version of each of them and until that happens these plugins don't work as they are outdated. The outcome of that scenario is clear - nobody uses PluginManager as they install plugins manually, so they work after the update.

> Also the current system is a little flawed as it relies on the server owner to provide a Personal Auth Token and as far as I know
PAT is only needed to access private repositories and to bypass rate limits. If you use only public plugins and you don't mass install them, you don't need to provide PAT.

So realistically the only issue you are trying to solve is difficulty to find plugins, right?

**Comment by ALEXWARELLC** [comment]
I guess. It is one of the major reasons that tho is whole thing was started. There strangely isn't an easy directory of plugins as you have to find them all over the internet.

**Comment by zabszk** [comment]
There is such directory on the NWAPI Discordbserver, just like on EXILED.

Before rewriting a lot of the code always try to improve what already exists, and if not possivle then discuss the rewrite. Rewrites aren't a thing that is done on daily basis.

Additionally, there was an idea to create a list of popular plugins and PluginManager supports it. Due to some internal changes in NW no plugin was added to that list, but the API exists and LA uses it. However it's not any kind of list of approved plugins, LA can install any plugin.

**Comment by ALEXWARELLC** [comment]
I see. Well no one really responds to messages and without any way to know a list of plugins exists, it was overlooked during the initial creation of the idea/issue. I'll take the L on this one.

**Comment by zabszk** [comment]
> I see. Well no one really responds to messages and without any way to know a list of plugins exists or was going to exist, it was overlooked during the initial creation of the idea/issue. I'll take the L on this one.

I assume you asked these questions on serverhost-chat. That channel is mainly for discussions between server owners. There is a big possibility that one of few people in charge of NW API and LA didn't notice these messages. Github issues exist. They can be (or even should be) used for discussions about ideas, before they are implemented.

Additionally reworking the PluginManager wouldn't resolve the issue. If the original issue was lack of a server list, reworking PluginAPI wouldn't change that - there still wouldn't be such list.
